default: &default
  adapter: mysql2
  encoding: utf8
  host: 127.0.0.1
  pool: 5
  username: root


development:
  <<: *default
  database: ppu_development
  username: root


test:
  <<: *default
  database: ppu_test

production:
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: ppu_production
  username: root
  password: PpU-Serv3R+SqL_2014
  host: 127.0.0.1
