default: &default
  adapter: mysql2
  encoding: utf8
  host: db
  pool: 5
  database: ppu_react
  username: root
  password: my-secret-pw

development:
  <<: *default
  database: ppu_react
  username: root
  password: my-secret-pw

test:
  <<: *default
  database: ppu_test

production:
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: ppu_react
  username: root
  password: my-secret-pw
