# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5eeb70065f1566c80b5db4a70ed712e498490f38783d58b8d933c683b370a4e84ba865c009991c36970574fe4b20c333c1354afe2e061b166db1c0812af14d0

test:
  secret_key_base: c87912e0acf652f6d60893ae207df3e7ff4831c26f4496deef31cd52a19936f3f01b1104feac77b3fe8cdeaee96afbec2dc0a31978d1a73dc77b999e0bbcbb86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
